/** Codes d'erreur du module document (convention de routing : cf. shared/http). */
export const DOCUMENT_ERROR_CODES = {
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  INVALID_DOCUMENT_TITLE: 'INVALID_DOCUMENT_TITLE',
  INVALID_DOCUMENT_SIZE: 'INVALID_DOCUMENT_SIZE',
  INVALID_RIGHTS_ATTESTATION: 'INVALID_RIGHTS_ATTESTATION',
  INVALID_DOCUMENT_UPLOAD: 'INVALID_DOCUMENT_UPLOAD',
} as const;

export type DocumentErrorCode = (typeof DOCUMENT_ERROR_CODES)[keyof typeof DOCUMENT_ERROR_CODES];
